### ISSUE TITLE
Kofam search yields TC bit threshhold error

### ISSUE THREAD

**Issue by morgvevans** [elizabethmcd/metabolisHMM#42]
Hi,
I was able to use summarize-metabolism but when using the search-custom-markers with the kofam database, I am running into some issues and I suspect it's some way the program is calling kofamscan?

Here's my command:
search-custom-markers --input bins_aa --output vitaminb3_bins_out_01062020 --markers_dir profiles/vitaminb3/ --markers_list vitaminb3_list.txt --metadata bin_metadata.csv --kofam kofamscan-1.1.0/exec_annotation --ko_list ko_list

The error I get is: TC bit threshholds unavailable on model K0xxxx (for all the KO's I listed).
I get results but it's totally blank/empty.

I am calling the executable (exec_annotation) and the ko_list should have the threshholds within. I tried running kofamscan on it's own without issue. I downloaded the dependencies required for kofamscan in the metabolishmm conda env (ruby, parallel). Even my config.yml should be correct although I'm not sure that matters since metabolishmm is calling kofamscan. 

Let me know if you know if a fix for this! Thank you very much!

**Comment by elizabethmcd** [comment]
Sorry, I messed up the documentation for this part and will fix it soon. I believe the only fix you need to do is the --kofam argument needs to be ON, and not pointing to the kofamscan executable. metabolisHMM will run the HMMs, that additional argument is so the program knows it needs to look for the external threshold cutoffs, which is the --ko_list argument I believe as you have it. So your command should be: 

`search-custom-markers --input bins_aa --output vitaminb3_bins_out01062020 --markers_dir profiles/vitaminb3/ --markers_list vitaminb3_list.txt --metadata bin_metadata.csv --kofam ON --ko_list ko_list` 

Let me know if this doesn't work, and sorry about the incorrect documentation.

**Comment by morgvevans** [comment]
Yes it worked, thank you so much!
