### ISSUE TITLE
make-heatmap.R  script location? 

### ISSUE THREAD

**Issue by Binvir** [elizabethmcd/metabolisHMM#44]
Hi Elizabeth, 

Thank you for this awesome tool! I am interested in using the summarize metabolism workflow, but I am unable to locate the "make-heatmap.R" script that is mentioned to be a requirement. Could you please let me know where I could access this script? 

Thanks! 
Binvir

**Comment by elizabethmcd** [comment]
Hello, 

What version of metabolisHMM are you using? The newest version shouldn't require that R script and instead does all the plotting within python. Additionally, where did you read that the R script is a requirement? I may have missed fixing that that no longer is a requirement in the documentation. 

Thanks for testing!

**Comment by Binvir** [comment]
Hi Elizabeth, 

My mistake - I haven't started using the tool yet. I am referring to the wiki https://github.com/elizabethmcd/metabolisHMM/wiki/Workflows#search-custom-markers in the "Summarize metabolism" section. Thank you for the punctual response!

**Comment by elizabethmcd** [comment]
I fixed the Wiki documentation, and working on fixing the pipeline help menus so it doesn't reflect this anymore. There is a known issue when using the `--aggregate` option when plotting, so if you try it out and have that error report it in issue #41
