### ISSUE TITLE
Hmmsearch crashes at search-custom-markers

### ISSUE THREAD

**Issue by nikobiota** [elizabethmcd/metabolisHMM#53]
Hi there, 

Thanks for the tool! 
I installed it via conda and am trying to run a custom marker search with the code
`search-custom-markers --input genomes/ --output output_t6ss/ --markers_dir profiles/ --markers_list t6ss --metadata metadata.csv --summary sum.csv --heatmap heat.pdf --kofam ON --ko_list ko_list`
which results in the  error below after the genome conversion. 
Any suggestion as how to fix would be appreciated!  

metabolisHMM v2.21
Reformatting fasta files...
Running HMM searches using custom marker set...
Traceback (most recent call last):
  File "/home/niko/miniconda2/envs/metabolishmm/bin/search-custom-markers", line 4, in <module>
    __import__('pkg_resources').run_script('metabolisHMM==2.22', 'search-custom-markers')
  File "/home/niko/miniconda2/envs/metabolishmm/lib/python3.9/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/niko/miniconda2/envs/metabolishmm/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/home/niko/miniconda2/envs/metabolishmm/lib/python3.9/site-packages/metabolisHMM-2.22-py3.9.egg/EGG-INFO/scripts/search-custom-markers", line 188, in <module>
    cmd = ["hmmsearch","-T"+tc,"--tblout="+outname,infile,genome]
TypeError: can only concatenate str (not "NoneType") to str

**Comment by elizabethmcd** [comment]
Just to double check - did you download the HMM profiles from the KofamKoala distribution, including the `ko_list` file? The threshold cutoff score should be coming from the `ko_list` file since the HMMs within the KofamKoala distribution don't have the TC written in the HMM file itself. Otherwise it might be an issue with how this program runs the hmmsearch command, so I will double check on that end as well.

**Comment by elizabethmcd** [comment]
I just tested this version with a set of HMMs from the KofamKoala distribution, and it passes the hmmsearch step and runs to completion. It might be that whatever is in your `t6ss` list isn't in the `profiles` folder that came with the KofamKOALA distribution, and therefore doesn't have a TC score in the `ko_list` file. Try checking this or how you have your `t6ss` file formatted. It should look like for example:
```
K00022.hmm
K00232.hmm
K00249.hmm
K00255.hmm
K00632.hmm
```
Where `.hmm` is included for every KO file in the list.

**Comment by nikobiota** [comment]
Thanks a lot for the rapid reply, much appreciated! 
Reading your reply made me immediately feel dumb, cause indeed the .hmm was not included in my marker list :D 
Now it runs without any issues, so thanks again for helping me!
